### ISSUE TITLE
希望导航栏白条沉浸

### ISSUE THREAD

**Issue by sanchendumeng** [Zhoucheng133/netPlayer-Mobile#2]
目前应用底部显示黑边，播放界面如果能够完善下就好了
![Screenshot_20240311-034747](https://github.com/Zhoucheng133/netPlayer-Mobile/assets/48471389/8d87b146-900e-4613-ab60-41a171b47fa5)
参考一下这样是不是很有MD
感谢你的作品！加油！

**Comment by Zhoucheng133** [comment]
> 目前应用底部显示黑边

可以给个截图给我参考一下会出现怎么样的黑边

**Comment by sanchendumeng** [comment]
![Uploading Screenshot_20240311-140528.png…]()

**Comment by sanchendumeng** [comment]
[
![Screenshot_20240311-140840](https://github.com/Zhoucheng133/netPlayer-Mobile/assets/48471389/0a5b801d-aa17-4041-9e08-78fd22bebd3c)
](url)

**Comment by sanchendumeng** [comment]
> > 目前应用底部显示黑边
> 
> 可以给个截图给我参考一下会出现怎么样的黑边



> > 目前应用底部显示黑边
> 
> 可以给个截图给我参考一下会出现怎么样的黑边

![Uploading Screenshot_20240311-140840.png…]()

**Comment by sanchendumeng** [comment]
![Uploading Screenshot_20240311-140840.png…]()

**Comment by sanchendumeng** [comment]
![Uploading Screenshot_20240311-140840_结果.jpg…]()

**Comment by sanchendumeng** [comment]
@
![Uploading Screenshot_20240311-140840_结果.jpg…]()

**Comment by Zhoucheng133** [comment]
已经了解到这个问题并已经在修复ing

将于下一个版本修复，修复成功后我会关闭这个issue

另外关于播放页面的改进意见，感谢你的建议，我会尝试改进它！

**Comment by sanchendumeng** [comment]
感谢你的努力 谢谢

**Comment by Zhoucheng133** [comment]
已在[v1.5.4](https://github.com/Zhoucheng133/netPlayer-Mobile/releases/tag/v1.5.4)中修复
