### ISSUE TITLE
只能显示500首歌曲，什么时候能显示全吗？

### ISSUE THREAD

**Issue by Ttong6** [Zhoucheng133/netPlayer-Mobile#4]
希望越来越好

**Comment by Zhoucheng133** [comment]
很遗憾，Subsonic API并不支持“显示所有歌曲”的功能，本软件能看到的所有歌曲是通过获取500首随机歌曲排序后得到的（[这个API参见这里](https://www.subsonic.org/pages/api.jsp#getRandomSongs)，500首是支持的最大数量）。
理论上可以实现真正意义上的“所有歌曲”，即通过获取所有专辑=>挨个展开所有专辑的歌曲，这样的确可以实现真正意义上的“所有歌曲”，但是网络请求的并发量太大了。
你可以通过标题栏右侧随机播放按钮来随机播放所有歌曲，这个功能不受显示的500首歌曲限制，会随机播放你歌单里的任意一首歌曲。

**Comment by Zhoucheng133** [comment]
> 很遗憾，Subsonic API并不支持“显示所有歌曲”的功能，本软件能看到的所有歌曲是通过获取500首随机歌曲排序后得到的（[这个API参见这里](https://www.subsonic.org/pages/api.jsp#getRandomSongs)，500首是支持的最大数量）。 理论上可以实现真正意义上的“所有歌曲”，即通过获取所有专辑=>挨个展开所有专辑的歌曲，这样的确可以实现真正意义上的“所有歌曲”，但是网络请求的并发量太大了。 你可以通过标题栏右侧随机播放按钮来随机播放所有歌曲，这个功能不受显示的500首歌曲限制，会随机播放你歌单里的任意一首歌曲。

抱歉论述错误，专辑数量也有显示的限制（500个专辑），因此如果要获取所有歌曲得获取所有艺人=>分别展开每个艺人的专辑=>展开每个专辑的歌曲
结论没有变化：网络请求并发量太大，不能用于实际app中
