### ISSUE TITLE
非常好的一个软件，希望增加在线播放选择音质功能。

### ISSUE THREAD

**Issue by kaige1116** [Zhoucheng133/netPlayer-Mobile#5]
很优质的软件，功能稍微简单。希望能增加在线播放选择音质功能。

**Comment by Zhoucheng133** [comment]
这个功能可以实现，但是会出现一个问题就是如果选择音质的话音乐流会以**直播流的形式**播放，也就是说这样的话会无法跳转时间轴，我会在下一个版本中尝试添加这个功能

**Comment by kaige1116** [comment]
👍🏻👍🏻👍🏻

**Comment by Zhoucheng133** [comment]
Add in [v2.0.6](https://github.com/Zhoucheng133/netPlayer-Mobile/releases/tag/v2.0.6)

不是很推荐用这个功能，受限于转码速度一方面可能无法定位时间轴，另一方面如果比特率过高可能会出现开头一段时间（大概几十秒）没有声音（也许是转码速度没跟上）。不过上述问题仅限于第一次播放，后面服务器缓存好了就没有这个问题了
