### ISSUE TITLE
[FR] 文件夹视图支持

### ISSUE THREAD

**Issue by fangxx3863** [Zhoucheng133/netPlayer-Mobile#6]
作者大大好

你开发的软件，UI界面设计优雅、响应速度快捷，使用体验非常出色。

我个人的音乐库数据量庞大，且由于歌曲类型多样，采用的分类方案也各不相同。目前，我主要依赖于文件夹的方式进行管理。

因此，我想咨询一下，您是否有计划在未来版本中加入对文件夹视图浏览的支持？这对于像我这样需要管理大量音乐文件的用户来说，将是一个极大的便利。

另外，我目前使用的是gonic服务端，不知道这一功能是否与其兼容？

期待作者大大的回复，再次感谢你为我们带来如此优秀的软件

**Comment by Zhoucheng133** [comment]
>依赖于文件夹管理

指的是服务器端以文件夹的形式存储然后在客户端上查看吗？有空我查阅一下API文档看看能不能实现

gonic我没用过，你可以找一下别的项目是否有支持

**Comment by fangxx3863** [comment]
subsonic是有文件夹API的  

```
getMusicFolders
http://your-server/rest/getMusicFolders Since [1.0.0](https://www.subsonic.org/pages/api.jsp#versions)

Returns all configured top-level music folders. 
Takes no extra parameters.

Returns a <subsonic-response> element with a nested <musicFolders> element on success. 

[Example](https://www.subsonic.org/pages/inc/api/examples/musicFolders_example_1.xml).
```

软件实现可以参考这两个APP  
[Tempo](https://github.com/CappielloAntonio/tempo)

[DSub](https://github.com/daneren2005/Subsonic)

**Comment by fangxx3863** [comment]
![Screenshot_2024-10-11-12-05-49-756_com cappielloantonio tempo](https://github.com/user-attachments/assets/60936be7-43ab-41b2-93c9-84c50ad9787a)
  
文件夹视图大概就是这种效果，和服务端音乐的目录结构一致  
gonic服务端拿的文件路径开头没有`/`，和别的服务端不太一样，需要特别处理一下，其他和标准API是一致的

**Comment by Zhoucheng133** [comment]
好的我知道了  
等我有空的时候研究一下吧，未来一阵子会有点忙

**Comment by fangxx3863** [comment]
期待大佬更新，不会Flutter帮不上忙（

**Comment by Zhoucheng133** [comment]
很遗憾地表示这个功能无法实现了 :(

由于我这边使用的是Navidrome作为音乐服务器，而Navidrome官方表示[并不支持这个功能（Not planned）](https://github.com/navidrome/navidrome/issues/739)

所以抱歉，我这边开发环境无法实现这个功能，你可以使用其它软件来实现
